version: '3'
services:
  spark:
    image: bitnami/spark:3.4.0
    container_name: pyspark-container
    volumes:
      - ./scripts:/app/scripts
    working_dir: /app
    command: ["pyspark"]
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master